services:
  redis-problem:
    image:
      'redis-problem:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    command: [ "--requirepass verysafepassword" ]
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - /path/to/local/d–∞ta:/root/redis
      - /path/to/local/redis.conf:/usr/local/etc/redis/redis.conf

  rcli:
    image: redis:latest
    links:
      - redis
    command: redis-cli -h redis